# Generated by Django 5.0.7 on 2024-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('phones', 'Phone'), ('shoes', 'Shoes'), ('clothes', 'Clothes')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('about', models.TextField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
