# Generated by Django 5.0.7 on 2024-10-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
